image: amaysim/serverless:3.21.0

stages:
  - deploy

deploy_development:
  stage: deploy
  before_script:
    - echo "Configuring container"
    - mkdir ~/.aws && touch ~/.aws/credentials
    - touch ~/.aws/config
    - touch queues.json
    - cat $AWS_CLI_CREDENTIALS >> ~/.aws/credentials
    - cat $AWS_CLI_CONFIG >> ~/.aws/config
  script:
    - echo "Deploying dev stack"
    - serverless deploy --stage $ENV_STAGE --region $AWS_REGION --param="AWS_REGION=${AWS_REGION}" --param="MONGODB_RSKYCLUSTER_REGION=${MONGODB_RSKYCLUSTER_REGION}" --param="MONGODB_RSKYCLUSTER_DATA_API_APP_ID=${MONGODB_RSKYCLUSTER_DATA_API_APP_ID}" --param="MONGODB_RSKYCLUSTER_DATA_API_KEY=${MONGODB_RSKYCLUSTER_DATA_API_KEY}" --param="MONGODB_RSKYCLUSTER_DATA_SOURCE=${MONGODB_RSKYCLUSTER_DATA_SOURCE}" --param="MONGODB_RSKYCLUSTER_DATABASE=${MONGODB_RSKYCLUSTER_DATABASE}" --param="MONGODB_RSKYCLUSTER_COINGECKO_TARGET_COINS_COLLECTION=${MONGODB_RSKYCLUSTER_COINGECKO_TARGET_COINS_COLLECTION}" --param="MONGODB_RSKYCLUSTER_COINGECKO_COINS_HISTORY_FAILED_COLLECTION=${MONGODB_RSKYCLUSTER_COINGECKO_COINS_HISTORY_FAILED_COLLECTION}" --param="SQS_QUEUE_REGION=${SQS_QUEUE_REGION}" --param="SQS_QUEUE_URL=${SQS_QUEUE_URL}" --verbose
  environment: development
  only:
    - development

remove_development:
  stage: deploy
  before_script:
    - echo "Configuring container"
    - mkdir ~/.aws && touch ~/.aws/credentials
    - touch ~/.aws/config
    - touch queues.json
    - cat $AWS_CLI_CREDENTIALS >> ~/.aws/credentials
    - cat $AWS_CLI_CONFIG >> ~/.aws/config
  script:
    - echo "Removing dev stack"
    - serverless remove --stage $ENV_STAGE --region $AWS_REGION --param="AWS_REGION=${AWS_REGION}" --param="MONGODB_RSKYCLUSTER_REGION=${MONGODB_RSKYCLUSTER_REGION}" --param="MONGODB_RSKYCLUSTER_DATA_API_APP_ID=${MONGODB_RSKYCLUSTER_DATA_API_APP_ID}" --param="MONGODB_RSKYCLUSTER_DATA_API_KEY=${MONGODB_RSKYCLUSTER_DATA_API_KEY}" --param="MONGODB_RSKYCLUSTER_DATA_SOURCE=${MONGODB_RSKYCLUSTER_DATA_SOURCE}" --param="MONGODB_RSKYCLUSTER_DATABASE=${MONGODB_RSKYCLUSTER_DATABASE}" --param="MONGODB_RSKYCLUSTER_COINGECKO_TARGET_COINS_COLLECTION=${MONGODB_RSKYCLUSTER_COINGECKO_TARGET_COINS_COLLECTION}" --param="MONGODB_RSKYCLUSTER_COINGECKO_COINS_HISTORY_FAILED_COLLECTION=${MONGODB_RSKYCLUSTER_COINGECKO_COINS_HISTORY_FAILED_COLLECTION}" --param="SQS_QUEUE_REGION=${SQS_QUEUE_REGION}" --param="SQS_QUEUE_URL=${SQS_QUEUE_URL}" --verbose
  environment: development
  only:
    - remove/development
