service: riskbloq-ahpf
deprecationNotificationMode: warn
configValidationMode: error

provider:
  name: aws
  runtime: python3.8
  timeout: 60
  layers:
    - arn:aws:lambda:${param:AWS_REGION}:770693421928:layer:Klayers-p38-pandas:6
    - arn:aws:lambda:${param:AWS_REGION}:770693421928:layer:Klayers-p38-requests:5
    - arn:aws:lambda:${param:AWS_REGION}:770693421928:layer:Klayers-p38-aws-xray-sdk:7
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: "*"
        - Effect: "Allow"
          Action:
            - s3:*
          Resource: "arn:aws:s3:::${param:TARGET_S3_BUCKET}/*"
        - Effect: "Allow"
          Action:
            - s3:ListBucket
          Resource: "arn:aws:s3:::${param:TARGET_S3_BUCKET}"
        - Effect: "Allow"
          Action:
            - sqs:*
          Resource: "arn:aws:sqs:*:828366613602:*"

functions:
  assets-history-producer:
    handler: handler.init_producer
    environment:
      TARGET_S3_BUCKET: ${param:TARGET_S3_BUCKET}
      TARGET_S3_ASSETS_DETAILS_PATH: ${param:TARGET_S3_ASSETS_DETAILS_PATH}
      TARGET_S3_ASSETS_DETAILS_FILENAME: ${param:TARGET_S3_ASSETS_DETAILS_FILENAME}
      QUEUE_LIST_FILENAME: ${param:QUEUE_LIST_FILENAME}
      TARGET_S3_ASSETS_HISTORY_LEAD_PATH: ${param:TARGET_S3_ASSETS_HISTORY_LEAD_PATH}
      TARGET_S3_ASSETS_HISTORY_FAILED_TAIL_PATH: ${param:TARGET_S3_ASSETS_HISTORY_FAILED_TAIL_PATH}
      TARGET_S3_ASSETS_HISTORY_SUCCESSFUL_TAIL_PATH: ${param:TARGET_S3_ASSETS_HISTORY_SUCCESSFUL_TAIL_PATH}
    events:
      - http:
          path: producer
          method: post
      - http:
          path: retry
          method: post
