service: rq-quant-anomaly-detect-producer
deprecationNotificationMode: warn
configValidationMode: error

provider:
  name: aws
  runtime: python3.9
  timeout: 30
  layers:
    - arn:aws:lambda:${param:AWS_REGION}:770693421928:layer:Klayers-p39-boto3:9
    - arn:aws:lambda:${param:AWS_REGION}:770693421928:layer:Klayers-p39-aws-xray-sdk:9
  tracing:
    apiGateway: true
    lambda: true
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - xray:PutTraceSegments
            - xray:PutTelemetryRecords
          Resource: "*"
        - Effect: "Allow"
          Action:
            - sqs:*
          Resource: "arn:aws:sqs:*:139699787534:*"

functions:
  func:
    handler: handler.init_producer
    environment:
      SQS_QUEUE_REGION: ${param:SQS_QUEUE_REGION}
      SQS_QUEUE_URL: ${param:SQS_QUEUE_URL}
    events:
      - http:
          path: producer
          method: post
